### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by EverNife** [MultiCubeUK/Another-Better-Chunk-Loader#2]
How to use it?

What is needed to use it?

**Comment by SamKemp** [comment]
Read the readme file
"Documentation to come, we want to get the plugin to a better point first"

This plugin was initially designed to just be used on the MultiCubeUK server as the new Chunk Loader plugin and wasn't intended for public/external use.
However I am no longer on the team that develop it so I cannot say its still necessarily the case

**Comment by EverNife** [comment]
![image](https://cloud.githubusercontent.com/assets/11357801/18732543/58abfbb2-803a-11e6-99f7-3ed54f5c04a5.png)

> 4 months ago

That is good time without commits... anyway.. I will assume that this project was dropped T.T

**Comment by SamKemp** [comment]
Thats about the time I left the team. I have seen that they have made a new repo
https://github.com/MultiCubeUKDevelopment/MultiCubeChunkLoader
